// oauth-code-react/src/App.js
import React, { Component } from 'react';
import './App.css';
import LogIn from './LogIn'

class App extends Component {
  render() {
    return (			
      <div className="App">
				<nav className="navbar navbar-default">
					<div className="container-fluid">
						<div className="navbar-header">
							<a className="navbar-brand" href="/">Spring Security OAuth - Authorization Code</a>
						</div>
					</div>
				</nav>
				<LogIn />
      </div>
    );
  }
}

export default App;

// oauth-code-angular/src/app/app.component.ts
import {Component} from '@angular/core';
 
@Component({
    selector: 'app-root',
    template: `<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Spring Security OAuth - Authorization Code</a>
    </div>
  </div>
</nav>
<router-outlet></router-outlet>`
})

export class AppComponent {}
